server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: root

  jpa:
    openInView: false
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

  data:
    jpa:
      repositories.enabled: true
      generate-ddl: true
      show-sql: true

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    es.eoi: DEBUG

